---
title: "Guardian articles"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
params:
  search: "COP26"
  days: 60
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, cache = FALSE, message = FALSE, warning = FALSE)
devtools::install_github("rstudio/miniUI")


```

```{r libraries}

library(guardianapi)
library(lubridate)
library(tidyverse)
devtools::install_github("julianflowers/myScrapers")
library(myScrapers)
library(textrank)
library(tidytext)
library(quanteda)
library(miniUI)
```

```{r get articles}


#key <- Sys.getenv("guardian_api")

guardianapi::gu_api_key(check_env = TRUE)

search_period <- guardianapi::gu_content(params$search, from_date = today() - days(params$days), to_date = today())

#glimpse(last_month)

search_period <- search_period %>%
  mutate(date = ymd(str_sub(web_publication_date, 1, 10))) %>%
  select(date, web_title, headline, body_text, short_url, section_name) %>%
  arrange(desc(date))


```


**Searches the Guardian for recent articles**

* Search term: *`r params$search`*
* Search period: `r glue::glue("Past ", params$days, " days")`
* No articles: `r nrow(search_period)`

```{r tldr}
search_period %>%
  DT::datatable(filter = "top")

```
