---
title: "Title analysis of core wildlife conservation journals"
author: "Julian Flowers"
date: "31/08/2021"
output: html_document
params: 
    search: "Journal of applied ecology"
---

```{r}

knitr::opts_chunk$set(echo = FALSE, cache = TRUE, message = FALSE, warning = FALSE)

devtools::install_github("julianflowers/myScrapers")

library(myScrapers)

library(tidyverse)

library(tictoc)
```


```{r}
tic()
search <- paste0(params$search, "[ta]")

ncbi_key <- Sys.getenv("ncbi_key")

n <- 10000

start <- 2000

end <- 2021

test <- pubmedAbstractR(search = search, n = n, ncbi_key = ncbi_key, start = start, end = end)
toc()
```

## annual counts

```{r}

test$abstracts %>%
   count(journal, year) %>%
   ggplot(aes(year, n, colour = journal, group = journal)) +
   geom_line() +
   viridis::scale_color_viridis(discrete = TRUE) +
   ggtitle(glue("Abstracts: ", {params$search}))
```

## keyword parse

### simple title analysis

```{r fig.height=8}


library(tidytext); library(quanteda)

word_freq <- test$abstracts %>%
  unnest_tokens(word, title, "words") %>%
  anti_join(stop_words) %>%
  filter(!str_detect(word, "\\d")) %>%
  count(journal, year, word, sort = T)

word_freq %>%
  filter(n > 4) %>%
  ggplot(aes(year, fct_rev(word), fill = n)) +
  geom_tile() +
  #facet_wrap(\~journal) +
  viridis::scale_fill_viridis(direction = -1) +
  theme_minimal()
```

### bigrams

```{r}
big <- create_bigrams(test$abstracts, title)

big <- big %>%
   count(year, bigram, sort = TRUE) %>%
   filter(n > 2)

big %>%
  ggplot(aes(year, fct_rev(bigram), fill = n)) +
  geom_tile() +
  viridis::scale_fill_viridis(direction = -1) + 
  theme_minimal()
```
